global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'victoria-metrics'
    static_configs:
      - targets: ['localhost:8428']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
